baseURL = 'https://Daisy2025769.github.io/'
languageCode = 'zh-cn'
title = 'Daisyçš„ä¸ªäººä¸»é¡µ' # è¿™é‡Œæ”¹æˆä½ çš„åå­—
theme = 'PaperMod'

[params]
  defaultTheme = "auto" # è‡ªåŠ¨è·Ÿéšç³»ç»Ÿåˆ‡æ¢é»‘ç™½æ¨¡å¼
  
  # å¼€å¯é¦–é¡µç®€ä»‹æ¨¡å¼
  [params.profileMode]
    enabled = true
    title = "Hi, I am Daisy ğŸ‘‹" # é¦–é¡µå¤§æ ‡é¢˜
    subtitle = "Welcome to my channel!" # å‰¯æ ‡é¢˜/ç®€ä»‹
    imageUrl = "avatar.jpg"
    imageTitle = "Avatar"
    imageWidth = 120
    imageHeight = 120

    # ç¤¾äº¤æŒ‰é’® (å¯ä»¥åŠ å¾®ä¿¡ã€Bç«™ã€é‚®ç®±ç­‰)
 [[params.profileMode.buttons]]
      name = "ğŸ“§ Email"  # æŒ‰é’®ä¸Šæ˜¾ç¤ºçš„æ–‡å­—ï¼Œå¯ä»¥åŠ ä¸ªemoji
      url = "mailto:web1091026187@gmail.com"  # âš ï¸æ³¨æ„ï¼šæŠŠè¿™é‡Œæ¢æˆä½ çš„çœŸå®é‚®ç®±
 [[params.profileMode.buttons]]
      name = "ğŸ“· Instagram"
      url = "https://www.instagram.com/web1091026187/"
  
  # é¡¶æ å¯¼èˆª
  [menu]
    [[menu.main]]
      identifier = "posts"
      name = "æ–‡ç« "
      url = "/posts/"
      weight = 10
    [[menu.main]]
      identifier = "search"
      name = "æœç´¢"
      url = "/search/"
      weight = 20